# Generated by Django 4.2.15 on 2024-08-30 10:39
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("remote_ip", models.GenericIPAddressField()),
                ("timestamp", models.DateTimeField()),
                ("method", models.CharField(max_length=10)),
                ("uri", models.CharField(max_length=255)),
                ("response_code", models.IntegerField()),
                ("response_size", models.IntegerField()),
            ],
        ),
    ]
